# Generated by Django 4.2.1 on 2023-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
