# Generated by Django 4.2.1 on 2023-06-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('veiculo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
    ]
