# Generated by Django 4.2.1 on 2023-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0004_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='porteiro',
            name='nivel',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='nivel', max_length=20),
            preserve_default=False,
        ),
    ]
