# Generated by Django 4.2.1 on 2023-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0007_porteiro_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='porteiro',
            name='tipo',
            field=models.CharField(default='gerente', max_length=20),
            preserve_default=False,
        ),
    ]
