# Generated by Django 4.2.1 on 2023-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0009_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroInter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('veiculo', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
                ('km_saida', models.IntegerField()),
                ('lacre_saida', models.CharField(max_length=20)),
                ('nfs_saida', models.CharField(max_length=50)),
                ('motorista', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('carga', models.CharField(max_length=50)),
                ('qtde_malotes_saida', models.IntegerField()),
                ('carga_extra', models.CharField(max_length=3)),
                ('especificacao_carga', models.CharField(max_length=100)),
            ],
        ),
    ]
