# Generated by Django 4.2.1 on 2023-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0011_alter_cadastrointer_carga_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer',
            name='especificacao_carga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
