# Generated by Django 4.2.1 on 2023-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0014_alter_cadastroterceiros_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cadastroterceiros',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
