# Generated by Django 4.2.1 on 2023-07-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0016_cadastrointerentrada_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrointerentrada',
            name='placa',
        ),
    ]
