# Generated by Django 4.2.1 on 2023-07-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0022_alter_cadastrointerentrada_km_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrointerentrada',
            name='placa',
        ),
    ]
