# Generated by Django 4.2.1 on 2023-07-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0024_cadastrointerentrada_placa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrointerentrada',
            old_name='placa',
            new_name='placa_entrada',
        ),
    ]
