# Generated by Django 4.2.1 on 2023-07-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0026_alter_cadastrointer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
