# Generated by Django 4.2.1 on 2023-07-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0027_alter_cadastrointer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTerceirosSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_saida', models.CharField(max_length=10)),
                ('data', models.DateTimeField()),
                ('descarga', models.BooleanField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('descarga_paga', models.BooleanField()),
                ('paletes_saida', models.IntegerField()),
                ('chapelex_saida', models.IntegerField()),
                ('nfs_prefixo_saida', models.IntegerField()),
                ('nfs_de_saida', models.IntegerField()),
                ('nfs_ate_saida', models.IntegerField()),
                ('nfs_exceto_saida', models.IntegerField()),
                ('nfs_apenas_saida', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cadastrointer',
            name='especificacao_carga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
