# Generated by Django 4.2.1 on 2023-07-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0028_cadastroterceirossaida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroterceirossaida',
            old_name='data',
            new_name='data_saida',
        ),
    ]
