# Generated by Django 4.2.1 on 2023-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0030_alter_cadastroterceirossaida_descarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrointer',
            name='outrosDestinos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
