# Generated by Django 4.2.1 on 2023-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0031_cadastrointer_outrosdestinos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_prefixo_saida',
            field=models.CharField(max_length=20),
        ),
    ]
