# Generated by Django 4.2.1 on 2023-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0032_alter_cadastroterceirossaida_nfs_prefixo_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_apenas_saida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_ate_saida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_de_saida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_exceto_saida',
            field=models.CharField(max_length=20),
        ),
    ]
