# Generated by Django 4.2.1 on 2023-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0033_alter_cadastroterceirossaida_nfs_apenas_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_apenas_saida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_ate_saida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_de_saida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_exceto_saida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastroterceirossaida',
            name='nfs_prefixo_saida',
            field=models.IntegerField(),
        ),
    ]
