# Generated by Django 4.2.1 on 2023-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0034_alter_cadastroterceirossaida_nfs_apenas_saida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroterceiros',
            name='nfs_apenas',
        ),
        migrations.RemoveField(
            model_name='cadastroterceiros',
            name='nfs_ate',
        ),
        migrations.RemoveField(
            model_name='cadastroterceiros',
            name='nfs_de',
        ),
        migrations.RemoveField(
            model_name='cadastroterceiros',
            name='nfs_exceto',
        ),
        migrations.RemoveField(
            model_name='cadastroterceiros',
            name='nfs_prefixo',
        ),
        migrations.AddField(
            model_name='cadastroterceiros',
            name='nfs',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
