# Generated by Django 4.2.1 on 2023-08-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0035_remove_cadastroterceiros_nfs_apenas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroterceirossaida',
            name='nfs_apenas_saida',
        ),
        migrations.RemoveField(
            model_name='cadastroterceirossaida',
            name='nfs_ate_saida',
        ),
        migrations.RemoveField(
            model_name='cadastroterceirossaida',
            name='nfs_de_saida',
        ),
        migrations.RemoveField(
            model_name='cadastroterceirossaida',
            name='nfs_exceto_saida',
        ),
        migrations.RemoveField(
            model_name='cadastroterceirossaida',
            name='nfs_prefixo_saida',
        ),
        migrations.AddField(
            model_name='cadastroterceirossaida',
            name='nfs',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
