# Generated by Django 5.0 on 2024-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0036_remove_cadastroterceirossaida_nfs_apenas_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroterceiros',
            name='produto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
