# Generated by Django 5.0 on 2024-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0037_cadastroterceiros_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroterceiros',
            name='nome',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
