# Generated by Django 5.0 on 2024-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0038_cadastroterceiros_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroterceiros',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
