# Generated by Django 5.0 on 2024-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0039_alter_cadastroterceiros_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrointer',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cadastrointerentrada',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
