# Generated by Django 5.0 on 2024-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0040_cadastrointer_status_cadastrointerentrada_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointerentrada',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
