# Generated by Django 5.0 on 2024-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0041_alter_cadastrointerentrada_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrointer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cadastrointerentrada',
            name='status',
        ),
    ]
