# Generated by Django 5.0 on 2024-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0042_remove_cadastrointer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroInter_Temporaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('veiculo', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
                ('km_saida', models.IntegerField()),
                ('lacre_saida', models.CharField(max_length=20)),
                ('nfs_saida', models.IntegerField()),
                ('motorista', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('carga', models.CharField(max_length=20)),
                ('qtde_malotes_saida', models.IntegerField()),
                ('carga_extra', models.CharField(max_length=5)),
                ('especificacao_carga', models.CharField(blank=True, max_length=100, null=True)),
                ('outrosDestinos', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
