# Generated by Django 5.0 on 2024-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0043_cadastrointer_temporaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer',
            name='nfs_saida',
            field=models.CharField(max_length=50),
        ),
    ]
