# Generated by Django 5.0 on 2024-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0044_alter_cadastrointer_nfs_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer',
            name='nfs_saida',
            field=models.IntegerField(),
        ),
    ]
