# Generated by Django 5.0 on 2024-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0045_alter_cadastrointer_nfs_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroterceiros',
            name='documento_motorista',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
