# Generated by Django 5.0 on 2024-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0046_cadastroterceiros_documento_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroterceiros',
            name='documento_motorista',
            field=models.IntegerField(),
        ),
    ]
