# Generated by Django 5.0 on 2024-05-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0047_alter_cadastroterceiros_documento_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer',
            name='nfs_saida',
            field=models.CharField(max_length=50),
        ),
    ]
