# Generated by Django 5.0 on 2024-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0048_alter_cadastrointer_nfs_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointerentrada',
            name='nfs_entrada',
            field=models.CharField(max_length=50),
        ),
    ]
