# Generated by Django 5.0 on 2024-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0049_alter_cadastrointerentrada_nfs_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer_temporaria',
            name='nfs_saida',
            field=models.CharField(max_length=50),
        ),
    ]
