# Generated by Django 5.1.1 on 2025-04-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0050_alter_cadastrointer_temporaria_nfs_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroterceiros',
            name='documento_motorista',
        ),
    ]
