# Generated by Django 5.0.4 on 2025-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0051_remove_cadastroterceiros_documento_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastrointer',
            name='nfs_saida',
            field=models.CharField(max_length=100),
        ),
    ]
