# Generated by Django 5.0.4 on 2025-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0052_alter_cadastrointer_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointer_temporaria',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastrointer_temporaria',
            name='nfs_saida',
            field=models.CharField(max_length=100),
        ),
    ]
