# Generated by Django 5.0.4 on 2025-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0053_alter_cadastrointer_temporaria_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrointerentrada',
            name='lacre_entrada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastrointerentrada',
            name='nfs_entrada',
            field=models.CharField(max_length=100),
        ),
    ]
